// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ltgampdtawuefwwayncx.supabase.co";
const configuredPublishableKey =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "sb_publishable_kaojo-PmyRSvPtpkKmG_mQ_tBdthZOD";

// Never abort module evaluation when a deployment forgot the public Supabase
// env. A thrown import leaves #root empty and gives users a white page with no
// actionable message. The app keeps a public project key fallback so ordinary
// deployments do not depend on a repeated Vercel setting; real API calls still
// fail closed if the public key is absent or revoked.
export const supabaseConfigurationMissing = !configuredPublishableKey;
const SUPABASE_PUBLISHABLE_KEY = configuredPublishableKey || "missing-publishable-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
